import useSWR from "swr";
import { useState } from "react";
import type { NextPage } from "next";

import Head from "next/head";
import Header from "../components/Header";
import Sync from "../components/Sync";

const Home: NextPage = () => {
  const [syncList, setSyncList] = useState(null);

  const empty = (
    <h1 className="text-center text-3xl  font-extrabold tracking-tight text-gray-900 sm:text-5xl pt-48">
      Welcome to Integrations back office
    </h1>
  );

  return (
    <div>
      <Head>
        <title>Integrations UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        onLookup={(integrationId, localEntity, localEntityRef) => {
          setSyncList(
            <Sync syncReq={{ integrationId, localEntity, localEntityRef }} />
          );
        }}
        onReset={() => setSyncList(null)}
      />

      <div className="container mx-auto pt-32">
        {syncList !== null ? syncList : empty}
      </div>
    </div>
  );
};

export default Home;
